DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'place_source_enum') THEN
    CREATE TYPE place_source_enum AS ENUM ('google', 'osm');
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS places (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source              place_source_enum NOT NULL DEFAULT 'google',
  source_place_id     TEXT NOT NULL,
  name                TEXT NOT NULL,
  formatted_address   TEXT,
  street              TEXT,
  city                TEXT,
  region              TEXT,
  country             TEXT,
  postal_code         TEXT,
  lat                 DOUBLE PRECISION NOT NULL,
  lon                 DOUBLE PRECISION NOT NULL,
  primary_type        TEXT,
  cuisine             TEXT,
  type_tags           TEXT,
  rating              NUMERIC(2,1),
  rating_count        INTEGER,
  price_level         SMALLINT,
  phone               TEXT,
  website_url         TEXT,
  map_url             TEXT,
  google_photo_reference   TEXT,
  cover_image_url     TEXT,
  cover_image_base64  TEXT,
  photo_gallery       JSONB,                       -- array of additional photos [{ id, image_base64, attribution }]
  has_photos          BOOLEAN NOT NULL DEFAULT FALSE,
  is_permanently_closed  BOOLEAN NOT NULL DEFAULT FALSE,
  opening_hours       JSONB,                       -- { weekday_text: string[], open_now: boolean }
  reviews             JSONB,                       -- array of reviews [{ author_name, rating, text, time }]
  international_phone_number TEXT,
  business_status     TEXT,                       -- OPERATIONAL, CLOSED_TEMPORARILY, etc.
  first_fetched_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at          TIMESTAMPTZ,
  raw_payload         JSONB,
  CONSTRAINT uq_places_source UNIQUE (source, source_place_id)
);

CREATE TABLE IF NOT EXISTS place_photos (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  place_id              BIGINT NOT NULL REFERENCES places(id) ON DELETE CASCADE,
  source_photo_id       TEXT NOT NULL,
  image_url             TEXT,
  image_base64          TEXT,
  width                 INTEGER,
  height                INTEGER,
  attribution           TEXT,
  is_primary            BOOLEAN NOT NULL DEFAULT FALSE,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_place_photos_source UNIQUE (place_id, source_photo_id)
);

CREATE TABLE IF NOT EXISTS coverage_tiles (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source          place_source_enum NOT NULL DEFAULT 'google',
  center_lat      DOUBLE PRECISION NOT NULL,
  center_lon      DOUBLE PRECISION NOT NULL,
  radius_m        INTEGER NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  query_hash      TEXT NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS idx_places_source_place_id
  ON places (source, source_place_id);

CREATE INDEX IF NOT EXISTS idx_places_lat_lon
  ON places (lat, lon);

CREATE INDEX IF NOT EXISTS idx_places_cuisine
  ON places (LOWER(cuisine));

CREATE INDEX IF NOT EXISTS idx_places_primary_type
  ON places (primary_type);

CREATE INDEX IF NOT EXISTS idx_place_photos_place_id
  ON place_photos (place_id);

CREATE INDEX IF NOT EXISTS idx_place_photos_primary
  ON place_photos (place_id, is_primary);

CREATE INDEX IF NOT EXISTS idx_places_expires_at
  ON places (expires_at) WHERE expires_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_places_last_updated
  ON places (last_updated_at) WHERE cover_image_base64 IS NOT NULL;


